import type { Metadata } from 'next'
import '../globals.css'
import { ReactNode } from 'react'
import NavigationBar from '@/components/navigation-bar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type AppLayoutProps = {
  children: ReactNode
}

export default function AppLayout({ children }: AppLayoutProps) {
  return (
    <html>
      <body>
        <NavigationBar />
        <main className='mx-auto w-2/3 pt-[150px]'>{children}</main>
      </body>
    </html>
  )
}
